### ISSUE TITLE
Unhandled panic resulting in stuck process

### ISSUE THREAD

**Issue by chien-splunk** [signalfx/signalfx-agent#1845]
We had some api server responsiveness problems resulting in some errors and one of them seemed to cause the agent to get wedged:

```
I0717 03:30:16.584885      25 trace.go:116] Trace[577905623]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108 (started: 2021-07-17 03:29:16.583756883 +0000 UTC m=+119377.399665026) (total time: 1m0.001106031s):
Trace[577905623]: [1m0.001106031s] [1m0.001106031s] END
E0717 03:30:16.584899      25 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Pod: the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
I0717 03:30:40.372234      25 trace.go:116] Trace[705045079]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108 (started: 2021-07-17 03:30:17.585087826 +0000 UTC m=+119438.400995807) (total time: 22.787126547s):
Trace[705045079]: [22.787126547s] [22.787126547s] END
E0717 03:30:40.372248      25 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Pod: Get https://SSS.SSS.SSS.SSS:443/api/v1/pods?fieldSelector=spec.nodeName%3Dip-NNN-NNN-NNN-NNN.redacted-region.compute.internal&limit=500: http2: server sent GOAWAY and closed the connection; LastStreamID=81, ErrCode=NO_ERROR, debug=""
E0717 03:31:17.387277      25 leaderelection.go:331] error retrieving resource lock <redacted>/signalfx-agent-leader: the server has received too many requests and has asked us to try again later (get configmaps signalfx-agent-leader)
I0717 03:31:42.490585      25 trace.go:116] Trace[1260169095]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108 (started: 2021-07-17 03:30:41.372419454 +0000 UTC m=+119462.188327450) (total time: 1m1.118126247s):
Trace[1260169095]: [1m1.118126247s] [1m1.118126247s] END
E0717 03:31:42.490611      25 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Pod: the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
I0717 03:32:43.492937      25 trace.go:116] Trace[208569304]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108 (started: 2021-07-17 03:31:43.490961304 +0000 UTC m=+119524.306869316) (total time: 1m0.001924437s):
Trace[208569304]: [1m0.001924437s] [1m0.001924437s] END
E0717 03:32:43.492952      25 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Pod: the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
I0717 03:33:39.935294      25 trace.go:116] Trace[594490460]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108 (started: 2021-07-17 03:32:44.493135113 +0000 UTC m=+119585.309043073) (total time: 55.442133607s):
Trace[594490460]: [55.442075316s] [55.442075316s] Objects listed
time="2021-07-17T03:33:39Z" level=error msg="Invalid K8s agent annotation" error="kubernetes config annotation agent.signalfx.com/config.8095.metricPath references invalid port number 8095"
time="2021-07-17T03:33:39Z" level=error msg="Invalid K8s agent annotation" error="kubernetes config annotation agent.signalfx.com/monitorType.8095 references invalid port number 8095"
E0717 03:33:40.094244      25 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x21efc60), concrete:(*runtime._type)(0x23ca7e0), asserted:(*runtime._type)(0x269dc20), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)
goroutine 473 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x228d440, 0xc000abf020)
/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x228d440, 0xc000abf020)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/signalfx/signalfx-agent/pkg/observers/kubernetes.(*Observer).watchPods.func3(0x23ca7e0, 0xc000c6fd60)
/usr/src/signalfx-agent/pkg/observers/kubernetes/api.go:168 +0x72
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/controller.go:212
k8s.io/client-go/tools/cache.newInformer.func1(0x22a3d60, 0xc000d90f20, 0x1, 0xc000d90f20)
/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/controller.go:376 +0x37f
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000f3e160, 0xc001310cf0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/delta_fifo.go:422 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000eeb100)
/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/controller.go:153 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000f75fb0)
/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002697fb0, 0x3b9aca00, 0x0, 0xc001572c01, 0xc0018c7380)
/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc000eeb100, 0xc0018c7380)
/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/controller.go:125 +0x2fd
created by github.com/signalfx/signalfx-agent/pkg/observers/kubernetes.(*Observer).watchPods
/usr/src/signalfx-agent/pkg/observers/kubernetes/api.go:172 +0x338
```

Looks watch informer might return other possible types than just the specified *v1.Pod.

In addition, it seems that the helm deployment doesn't include any liveness or readiness probes. Not sure if there's a healthcheck endpoint that would've caught this scenario but might be worth adding probes.

Agent image version 4.18.1

**Comment by keitwb** [comment]
Yeah that's probably a new thing in the API that we didn't encounter before with the deleted pod stand in.  

The warning about invalid port number is probably a configuration issue with your annotations.

This should cause the agent to crash which should cause the pod to end which should be easily detectable.

**Comment by dxu-sfx** [comment]
@keitwb If you want to check more in the container, please feel free. I did not bounce the failed pod yet. We can live like this for day or two. but not too long if you want more current log and stuff to debug

**Comment by keitwb** [comment]
The stack trace is clear enough.  I think https://github.com/signalfx/signalfx-agent/pull/1846 should fix it.  Will release a new patch soon.
