### ISSUE TITLE
Chef cookbook intermittently fails on first convergence on yum base

### ISSUE THREAD

**Issue by mitom** [signalfx/signalfx-agent#585]
yum occasionally fails to find the signalfx package in the repository and fails the chef run. Re-running chef without changes solves this. A potential fix could be to move to the [yum_repository](https://docs.chef.io/resource_yum_repository.html) resource instead of just writing the file? Or is this potentially an issue with the repository?

```
* yum_package[signalfx-agent] action install[2019-02-18T18:29:39+00:00] INFO: Processing yum_package[signalfx-agent] action install (signalfx_agent::default line 33)

* No candidate version available for signalfx-agent
================================================================================
Error executing action `install` on resource 'yum_package[signalfx-agent]'
================================================================================

    Chef::Exceptions::Package
-------------------------
No candidate version available for signalfx-agent

    Resource Declaration:
---------------------
# In /var/chef.cloudreach/cache/cookbooks/signalfx_agent/recipes/default.rb

     33: package 'signalfx-agent' do  # ~FC009
     34:   action :install
     35:   version node['signalfx_agent']['package_version'] if !node['signalfx_agent']['package_version'].nil?
     36:   options '--allow-downgrades' if platform_family?('debian') \
     37:     && node['packages']['apt'] \
     38:     && Gem::Version.new(node['packages']['apt']['version']) >= Gem::Version.new('1.1.0')
     39:   allow_downgrade true if platform_family?('rhel', 'amazon', 'fedora')
     40:   notifies :restart, 'service[signalfx-agent]', :delayed
     41: end
     42:

    Compiled Resource:
------------------
# Declared in /var/chef.cloudreach/cache/cookbooks/signalfx_agent/recipes/default.rb:33:in `from_file'

    yum_package("signalfx-agent") do
      package_name "signalfx-agent"
      action [:install]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "signalfx_agent"
      recipe_name "default"
      allow_downgrade true
    end

    System Info:
------------
chef_version=14.10.9
    platform=amazon
    platform_version=2018.03
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

**Comment by keitwb** [comment]
@mitom do you see this only when the `node['signalfx_agent']['package_version']` attribute has changed or even when it remains the same across chef runs?

**Comment by mitom** [comment]
I have seen it multiple times on the first convergence of an instance (i.e. the run that sets up the yum repository and installs the agent for the first time.) Have not seen it occur at a different time, but also have not changed the version number on running nodes yet.

**Comment by keitwb** [comment]
Ok, sounds like a race between adding the yum repo config and doing the install.  Perhaps it needs to trigger some kind of refresh in Yum/RPM to pick it up.

I think the reason we didn't use `yum_repository` is because it doesn't exist in Chef 12.1 (introduced in 12.14) which is what we targeted as the minimum Chef version supported.  I'll see what the rationale for that was and if we can't just make the minimum Chef version higher up in the 12.x series.

**Comment by mitom** [comment]
This seems to be still happening:
```
[2019-02-25T12:08:55+00:00] INFO: execute[yum-clean] ran successfully
- execute yum --disablerepo='*' --enablerepo='signalfx-agent' clean all
Recipe: signalfx_agent::default
* yum_package[signalfx-agent] action install[2019-02-25T12:08:55+00:00] INFO: Processing yum_package[signalfx-agent] action install (signalfx_agent::default line 38)

* No candidate version available for signalfx-agent
================================================================================
Error executing action `install` on resource 'yum_package[signalfx-agent]'
================================================================================

    Chef::Exceptions::Package
-------------------------
No candidate version available for signalfx-agent

    Resource Declaration:
---------------------
# In /var/chef.cloudreach/cache/cookbooks/signalfx_agent/recipes/default.rb

     38:   package 'signalfx-agent' do  # ~FC009
     39:     action :install
     40:     version node['signalfx_agent']['package_version'] if !node['signalfx_agent']['package_version'].nil?
     41:     options '--allow-downgrades' if platform_family?('debian') \
     42:       && node['packages']['apt'] \
     43:       && Gem::Version.new(node['packages']['apt']['version']) >= Gem::Version.new('1.1.0')
     44:     allow_downgrade true if platform_family?('rhel', 'amazon', 'fedora')
     45:     notifies :restart, "service[signalfx-agent]", :delayed
     46:   end
     47: end

    Compiled Resource:
------------------
# Declared in /var/chef.cloudreach/cache/cookbooks/signalfx_agent/recipes/default.rb:38:in `from_file'

    yum_package("signalfx-agent") do
      package_name "signalfx-agent"
      action [:install]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "signalfx_agent"
      recipe_name "default"
      allow_downgrade true
    end

    System Info:
------------
chef_version=14.10.9
    platform=amazon
    platform_version=2018.03
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

It's the same instance (it's in an ASG). The clean command ran - see top of output.

**Comment by mitom** [comment]
Actually, it seems this has made it worse. It seems to be unable to converge due to this even on repeated executions.
