### ISSUE TITLE
Chef won't update the package on windows

### ISSUE THREAD

**Issue by mitom** [signalfx/signalfx-agent#665]
The chef run will update the version file even if it fails to properly update the package. This means it won't even try to do it the next time and it will just silently ignore it. The version check should be based on the actual output of the agent, not a file so at least it keeps trying and failing. 

```
PS C:\> & 'C:\Program Files\SignalFx\SignalFxAgent\bin\signalfx-agent.exe' --version
agent-version: '4.0.2', built-time: '2019-02-22T12:35:01-08'
PS C:\>
PS C:\> chef-client
Starting Chef Client, version 14.11.21
[2019-03-26T12:07:58+00:00] INFO: *** Chef 14.11.21 ***
[2019-03-26T12:07:58+00:00] INFO: Platform: x64-mingw32
[2019-03-26T12:07:58+00:00] INFO: Chef-client pid: 1296
[2019-03-26T12:07:58+00:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
[2019-03-26T12:08:03+00:00] INFO: Run List is [recipe[signalfx_agent]]
[2019-03-26T12:08:03+00:00] INFO: Run List expands to [signalfx_agent]
[2019-03-26T12:08:03+00:00] INFO: Starting Chef Run for wint
[2019-03-26T12:08:03+00:00] INFO: Running start handlers
[2019-03-26T12:08:03+00:00] INFO: Start handlers complete.
[2019-03-26T12:08:03+00:00] INFO: Error while reporting run start to Data Collector. URL: https://base.chef.cloudreach.c
om/organizations/cloudreach-test-mock-environment/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if y
ou do not have Chef Automate)
resolving cookbooks for run list: ["signalfx_agent"]
[2019-03-26T12:08:04+00:00] INFO: Loading cookbooks [signalfx_agent@0.2.2, windows@5.2.3]
Synchronizing Cookbooks:
  - signalfx_agent (0.2.2)
  - windows (5.2.3)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 6 resources
Recipe: signalfx_agent::default
  * directory[\ProgramData\SignalFxAgent] action create[2019-03-26T12:08:04+00:00] INFO: Processing directory[\ProgramDa
ta\SignalFxAgent] action create (signalfx_agent::default line 20)
 (up to date)
Recipe: signalfx_agent::win
  * windows_zipfile[\Program Files\SignalFx\] action unzip[2019-03-26T12:08:04+00:00] INFO: Processing windows_zipfile[\
Program Files\SignalFx\] action unzip (signalfx_agent::win line 2)

    - unzip https://dl.signalfx.com/windows/final/zip/SignalFxAgent-4.2.0-win64.zip
    * remote_file[c:/chef/cache/SignalFxAgent-4.2.0-win64.zip] action create[2019-03-26T12:08:04+00:00] INFO: Processing
 remote_file[c:/chef/cache/SignalFxAgent-4.2.0-win64.zip] action create (c:/chef/cache/cookbooks/windows/resources/zipfi
le.rb line 40)
[2019-03-26T12:08:07+00:00] INFO: remote_file[c:/chef/cache/SignalFxAgent-4.2.0-win64.zip] created file c:/chef/cache/Si
gnalFxAgent-4.2.0-win64.zip

      - create new file c:/chef/cache/SignalFxAgent-4.2.0-win64.zip[2019-03-26T12:08:08+00:00] INFO: remote_file[c:/chef
/cache/SignalFxAgent-4.2.0-win64.zip] updated file contents c:/chef/cache/SignalFxAgent-4.2.0-win64.zip

      - update content in file c:/chef/cache/SignalFxAgent-4.2.0-win64.zip from none to 767f07
      (file sizes exceed 10000000 bytes, diff output suppressed)
    * ruby_block[Unzipping] action run[2019-03-26T12:08:08+00:00] INFO: Processing ruby_block[Unzipping] action run (c:/
chef/cache/cookbooks/windows/resources/zipfile.rb line 54)
[2019-03-26T12:08:13+00:00] INFO: ruby_block[Unzipping] called

      - execute the ruby block Unzipping

  * file[\Program Files\SignalFx\\version.txt] action create[2019-03-26T12:08:13+00:00] INFO: Processing file[\Program F
iles\SignalFx\\version.txt] action create (signalfx_agent::win line 11)
[2019-03-26T12:08:13+00:00] INFO: file[\Program Files\SignalFx\\version.txt] backed up to c:/chef/backup\Program Files\S
ignalFx\\version.txt.chef-20190326120813.853506
[2019-03-26T12:08:13+00:00] INFO: file[\Program Files\SignalFx\\version.txt] updated file contents \Program Files\Signal
Fx\\version.txt

    - update content in file \Program Files\SignalFx\\version.txt from 5fde70 to 96507e
    --- \Program Files\SignalFx\\version.txt    2019-03-26 12:06:56.563825400 +0000
    +++ \Program Files\SignalFx/chef-version20190326-1296-1cu0dtj.txt   2019-03-26 12:08:13.837742400 +0000
    @@ -1,2 +1,2 @@
    -4.0.2
    +4.2.0
  * powershell_script[ensure service created] action run[2019-03-26T12:08:13+00:00] INFO: Processing powershell_script[e
nsure service created] action run (signalfx_agent::win line 23)
[2019-03-26T12:08:14+00:00] INFO: powershell_script[ensure service created] ran successfully

    - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionP
olicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/2/chef-script20190326-1296-1uf2ibj.ps1"
Recipe: signalfx_agent::default
  * template[\ProgramData\SignalFxAgent\agent.yaml] action create[2019-03-26T12:08:14+00:00] INFO: Processing template[\
ProgramData\SignalFxAgent\agent.yaml] action create (signalfx_agent::default line 47)
 (up to date)
  * windows_service[signalfx-agent] action enable[2019-03-26T12:08:14+00:00] INFO: Processing windows_service[signalfx-a
gent] action enable (signalfx_agent::default line 55)
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1086:in `rescue in block in s
ervices' : WARNING: Failed to retrieve description for the CDPUserSvc_93d7e service. (StructuredWarnings::StandardWarnin
g)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1099:in `rescue in block in
 services' : WARNING: Unable to get delayed auto start information for the CDPUserSvc_93d7e service (StructuredWarnings:
:StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1157:in `res
cue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_93d7e service (StructuredWarn
ings::StandardWarning) (up to date)
  * windows_service[signalfx-agent] action start[2019-03-26T12:08:14+00:00] INFO: Processing windows_service[signalfx-ag
ent] action start (signalfx_agent::default line 55)
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1086:in `rescue in block in s
ervices' : WARNING: Failed to retrieve description for the CDPUserSvc_93d7e service. (StructuredWarnings::StandardWarnin
g)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1099:in `rescue in block in
 services' : WARNING: Unable to get delayed auto start information for the CDPUserSvc_93d7e service (StructuredWarnings:
:StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1157:in `res
cue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_93d7e service (StructuredWarn
ings::StandardWarning) (up to date)
[2019-03-26T12:08:15+00:00] INFO: windows_zipfile[\Program Files\SignalFx\] sending restart action to windows_service[si
gnalfx-agent] (delayed)
  * windows_service[signalfx-agent] action restart[2019-03-26T12:08:15+00:00] INFO: Processing windows_service[signalfx-
agent] action restart (signalfx_agent::default line 55)
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1086:in `rescue in block in s
ervices' : WARNING: Failed to retrieve description for the CDPUserSvc_93d7e service. (StructuredWarnings::StandardWarnin
g)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1099:in `rescue in block in
 services' : WARNING: Unable to get delayed auto start information for the CDPUserSvc_93d7e service (StructuredWarnings:
:StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1157:in `res
cue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_93d7e service (StructuredWarn
ings::StandardWarning)[2019-03-26T12:08:16+00:00] INFO: windows_service[signalfx-agent] configured.
[2019-03-26T12:08:17+00:00] INFO: windows_service[signalfx-agent] restarted

    - restart service windows_service[signalfx-agent]
[2019-03-26T12:08:17+00:00] INFO: Chef Run complete in 13.800471 seconds

Running handlers:
[2019-03-26T12:08:17+00:00] INFO: Running report handlers
Running handlers complete
[2019-03-26T12:08:17+00:00] INFO: Report handlers complete
Chef Client finished, 6/10 resources updated in 18 seconds
PS C:\> & 'C:\Program Files\SignalFx\SignalFxAgent\bin\signalfx-agent.exe' --version
agent-version: '4.0.2', built-time: '2019-02-22T12:35:01-08'
```

As per the above, the file gets updated:
```
    -4.0.2
    +4.2.0
```

But the actual version doesn't change. It's also the only cookbook in the runlist.

**Comment by mitom** [comment]
To note here: this is an empty run for the sake of testing this. Including configuration that requires 4.2.0 (such as the realm) causes an error for the agent and it stops reporting. The windows service also times out.

**Comment by jchengsfx** [comment]
Thank you for reporting this @mitom . We are currently looking into this and will follow up soon with a resolution.

**Comment by jchengsfx** [comment]
@mitom We identified the issue and released v0.2.3 of the cookbook to chef supermarket. Please let us know if you still run into this issue.

**Comment by mitom** [comment]
Thank you, it addresses the issue of not being able to update. It will still not re-attempt to update if it failed, but it addresses the critical nature of this issue.

**Comment by jchengsfx** [comment]
Thanks @mitom . Closing this since the primary issue has been addressed with the latest cookbook release.
